events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /health {
            default_type application/json;
            return 200 '{"service":"product-service","status":"healthy"}';
        }

        location /api/products {
            default_type application/json;
            return 200 '{"products":["laptop","phone","tablet"]}';
        }
    }
}
